name: Continuous integration

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  app-tests:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install NPM dependencies
        run: npm install

      - name: Check javaScript code style
        run: npm run lint

      - name: Execute javaScript tests
        run: npm run coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}